// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rafty.proto

/*
Package rafty is a generated protocol buffer package.

It is generated from these files:
	rafty.proto

It has these top-level messages:
	Attribute
	Node
	JoinRequest
	JoinResponse
	ListRequest
	ListResponse
	RequestVoteRequest
	RequestVoteResponse
	HeartbeatRequest
	HeartbeatResponse
	AnnounceLeaderRequest
	AnnounceLeaderResponse
*/
package rafty

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Attribute struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Attribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Node struct {
	Id         string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Host       string       `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,3,rep,name=attributes" json:"attributes,omitempty"`
	Status     string       `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Node) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type JoinRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JoinRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type JoinResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JoinResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListRequest struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type ListResponse struct {
	Nodes []int32 `protobuf:"varint,1,rep,packed,name=nodes" json:"nodes,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListResponse) GetNodes() []int32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type RequestVoteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RequestVoteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RequestVoteResponse struct {
	Vote bool `protobuf:"varint,1,opt,name=vote" json:"vote,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RequestVoteResponse) GetVote() bool {
	if m != nil {
		return m.Vote
	}
	return false
}

type HeartbeatRequest struct {
	Leader string  `protobuf:"bytes,1,opt,name=leader" json:"leader,omitempty"`
	Data   string  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Nodes  []*Node `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *HeartbeatRequest) Reset()                    { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()               {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *HeartbeatRequest) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *HeartbeatRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *HeartbeatRequest) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type HeartbeatResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *HeartbeatResponse) Reset()                    { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()               {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *HeartbeatResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AnnounceLeaderRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AnnounceLeaderRequest) Reset()                    { *m = AnnounceLeaderRequest{} }
func (m *AnnounceLeaderRequest) String() string            { return proto.CompactTextString(m) }
func (*AnnounceLeaderRequest) ProtoMessage()               {}
func (*AnnounceLeaderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AnnounceLeaderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AnnounceLeaderResponse struct {
	// Consent refers to `consent given`
	// we can define certain parameters
	// in future, such as aspects of the
	// new leader which could be incompatible
	// with one or more followers, which would
	// allow the node to die instead of connecting
	// I.e. can some nodes only talk to leaders
	// on a certain network range or partition?
	Consent bool `protobuf:"varint,1,opt,name=consent" json:"consent,omitempty"`
}

func (m *AnnounceLeaderResponse) Reset()                    { *m = AnnounceLeaderResponse{} }
func (m *AnnounceLeaderResponse) String() string            { return proto.CompactTextString(m) }
func (*AnnounceLeaderResponse) ProtoMessage()               {}
func (*AnnounceLeaderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AnnounceLeaderResponse) GetConsent() bool {
	if m != nil {
		return m.Consent
	}
	return false
}

func init() {
	proto.RegisterType((*Attribute)(nil), "rafty.Attribute")
	proto.RegisterType((*Node)(nil), "rafty.Node")
	proto.RegisterType((*JoinRequest)(nil), "rafty.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "rafty.JoinResponse")
	proto.RegisterType((*ListRequest)(nil), "rafty.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "rafty.ListResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "rafty.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "rafty.RequestVoteResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "rafty.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "rafty.HeartbeatResponse")
	proto.RegisterType((*AnnounceLeaderRequest)(nil), "rafty.AnnounceLeaderRequest")
	proto.RegisterType((*AnnounceLeaderResponse)(nil), "rafty.AnnounceLeaderResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rafty service

type RaftyClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	AnnounceLeader(ctx context.Context, in *AnnounceLeaderRequest, opts ...grpc.CallOption) (*AnnounceLeaderResponse, error)
}

type raftyClient struct {
	cc *grpc.ClientConn
}

func NewRaftyClient(cc *grpc.ClientConn) RaftyClient {
	return &raftyClient{cc}
}

func (c *raftyClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := grpc.Invoke(ctx, "/rafty.Rafty/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftyClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/rafty.Rafty/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftyClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/rafty.Rafty/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftyClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := grpc.Invoke(ctx, "/rafty.Rafty/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftyClient) AnnounceLeader(ctx context.Context, in *AnnounceLeaderRequest, opts ...grpc.CallOption) (*AnnounceLeaderResponse, error) {
	out := new(AnnounceLeaderResponse)
	err := grpc.Invoke(ctx, "/rafty.Rafty/AnnounceLeader", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rafty service

type RaftyServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	AnnounceLeader(context.Context, *AnnounceLeaderRequest) (*AnnounceLeaderResponse, error)
}

func RegisterRaftyServer(s *grpc.Server, srv RaftyServer) {
	s.RegisterService(&_Rafty_serviceDesc, srv)
}

func _Rafty_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftyServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rafty.Rafty/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftyServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rafty_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftyServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rafty.Rafty/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftyServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rafty_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftyServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rafty.Rafty/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftyServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rafty_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftyServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rafty.Rafty/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftyServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rafty_AnnounceLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftyServer).AnnounceLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rafty.Rafty/AnnounceLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftyServer).AnnounceLeader(ctx, req.(*AnnounceLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rafty_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rafty.Rafty",
	HandlerType: (*RaftyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Rafty_Join_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Rafty_List_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Rafty_RequestVote_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Rafty_Heartbeat_Handler,
		},
		{
			MethodName: "AnnounceLeader",
			Handler:    _Rafty_AnnounceLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rafty.proto",
}

func init() { proto.RegisterFile("rafty.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x6d, 0xbe, 0x16, 0x76, 0x52, 0x55, 0x61, 0x0a, 0x4b, 0x88, 0x00, 0x6d, 0x2d, 0x24, 0xc2,
	0x81, 0x8a, 0x6e, 0xff, 0x00, 0xe5, 0x80, 0x10, 0xaa, 0x40, 0xca, 0x81, 0xbb, 0x37, 0x31, 0x22,
	0xa2, 0x8a, 0x4b, 0x3c, 0xa9, 0xd4, 0x7f, 0xc8, 0xcf, 0x42, 0x76, 0x6c, 0x93, 0xfd, 0x92, 0x7a,
	0x9b, 0x67, 0xbf, 0x79, 0xf3, 0x3c, 0x4f, 0x86, 0xb4, 0xe7, 0x3f, 0xe9, 0xfe, 0xfc, 0xb6, 0x97,
	0x24, 0x31, 0x31, 0x80, 0x5d, 0xc2, 0xfc, 0x8a, 0xa8, 0x6f, 0xd7, 0x03, 0x09, 0xcc, 0x20, 0xfa,
	0x2d, 0xee, 0xf3, 0x60, 0x19, 0x94, 0xf3, 0x4a, 0x97, 0xf8, 0x14, 0x92, 0x3b, 0x7e, 0x33, 0x88,
	0x3c, 0x34, 0x67, 0x23, 0x60, 0x04, 0xf1, 0x37, 0xd9, 0x08, 0x3c, 0x81, 0xb0, 0x6d, 0x2c, 0x3d,
	0x6c, 0x1b, 0x44, 0x88, 0x7f, 0x49, 0x45, 0x96, 0x6c, 0x6a, 0xfc, 0x00, 0xc0, 0xdd, 0x00, 0x95,
	0x47, 0xcb, 0xa8, 0x4c, 0x57, 0xd9, 0xf9, 0xe8, 0xc4, 0x4f, 0xae, 0x26, 0x1c, 0x5c, 0xc0, 0x4c,
	0x11, 0xa7, 0x41, 0xe5, 0xb1, 0xd1, 0xb1, 0x88, 0x5d, 0x40, 0xfa, 0x55, 0xb6, 0x5d, 0x25, 0xfe,
	0x0c, 0x42, 0xd1, 0x43, 0x86, 0xb3, 0xd7, 0x70, 0x3c, 0xb6, 0xa8, 0x5b, 0xd9, 0xa9, 0x1d, 0xc3,
	0xec, 0x0c, 0xd2, 0xeb, 0x56, 0x91, 0x93, 0x74, 0x12, 0xc1, 0x44, 0xa2, 0x84, 0xe3, 0x91, 0x62,
	0x25, 0x72, 0x48, 0x3a, 0xd9, 0x08, 0x95, 0x07, 0xcb, 0xa8, 0x4c, 0x3e, 0x85, 0x59, 0x50, 0x8d,
	0x07, 0xec, 0x0d, 0xa0, 0x15, 0xfa, 0x21, 0x49, 0x1c, 0xb0, 0xc9, 0xde, 0xc1, 0xe9, 0x06, 0xcb,
	0xca, 0x22, 0xc4, 0x77, 0x92, 0x84, 0x21, 0x3e, 0xae, 0x4c, 0xcd, 0x38, 0x64, 0x5f, 0x04, 0xef,
	0x69, 0x2d, 0xb8, 0xb7, 0xb8, 0x80, 0xd9, 0x8d, 0xe0, 0x8d, 0xe8, 0xad, 0xa4, 0x45, 0xba, 0xbf,
	0xe1, 0xc4, 0xdd, 0xeb, 0x75, 0x8d, 0x67, 0xce, 0xea, 0xb8, 0xf5, 0xd4, 0x6e, 0x5d, 0x47, 0xe7,
	0x3c, 0xbf, 0x87, 0x27, 0x93, 0x11, 0xfe, 0x89, 0x8f, 0xd4, 0x50, 0xd7, 0x42, 0x29, 0x6b, 0xc7,
	0x41, 0xf6, 0x16, 0x9e, 0x5d, 0x75, 0x9d, 0x1c, 0xba, 0x5a, 0x5c, 0x9b, 0xb9, 0x87, 0x5e, 0xb9,
	0x82, 0xc5, 0x36, 0xf1, 0xbf, 0x78, 0xad, 0x8b, 0x8e, 0x9c, 0xb8, 0x85, 0xab, 0xbf, 0x21, 0x24,
	0x95, 0x76, 0x88, 0x17, 0x10, 0xeb, 0xd8, 0x10, 0xad, 0xe3, 0x49, 0xec, 0xc5, 0xe9, 0xc6, 0xd9,
	0x28, 0xca, 0x8e, 0x74, 0x8b, 0x8e, 0xc9, 0xb7, 0x4c, 0x62, 0xf5, 0x2d, 0xd3, 0x1c, 0xd9, 0x11,
	0x7e, 0x86, 0x74, 0x92, 0x04, 0xbe, 0xb0, 0xac, 0xdd, 0x0c, 0x8b, 0x62, 0xdf, 0x95, 0xd7, 0xf9,
	0x08, 0x73, 0xbf, 0x43, 0x7c, 0x6e, 0xa9, 0xdb, 0xc1, 0x15, 0xf9, 0xee, 0x85, 0x57, 0xf8, 0x0e,
	0x27, 0x9b, 0xdb, 0xc2, 0x97, 0xee, 0x87, 0xec, 0xdb, 0x76, 0xf1, 0xea, 0xc0, 0xad, 0x13, 0x5c,
	0xcf, 0xcc, 0x1f, 0xbf, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x80, 0x9d, 0x5a, 0xf2, 0x03,
	0x00, 0x00,
}
